title:              Andre's Blog
email:              goldfishandrobin@gmail.com
description:        collecting biology data
author:             Andre Mones
baseurl:            "/smartblog"
url:                "https://goldfishthebrave.github.io"

# Social Profiles
twitter_username:   
github_username:    goldfishthebrave
facebook_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: goldfishthebrave-github-io